### ISSUE TITLE
refactor(RESTful backend API)

### ISSUE THREAD

**Issue by zhanyeye** [nju-softeng/dingtalk-app-server#61]
项目前期因为 钉钉小程序只支持 GET,POST，我调研也不够，导致[controller](https://github.com/nju-softeng/dingtalk-app-back-end/tree/main/src/main/java/com/softeng/dingtalk/controller)接口设计不遵循规范，建议重构接口。

**Comment by lilingj** [comment]
记得之前我在哪个分支上看到一个说明，说钉钉只支持get、post方法。如果是这样，就没办法设计RESTFul风格的接口了吧

**Comment by zhanyeye** [comment]
对呀对呀，我之前也担心过，我给你解释一下：
是钉钉小程序只支持 get, post, 所以可能会不兼容钉钉小程序~，1. 我们目前不用开发钉钉小程序.
2. 其实我们可以通过在前端请求时在http head做一些封装，解决这个问题。
&nbsp;


詹泽晔
***@***.***

南京大学&nbsp;软件学院&nbsp;22届&nbsp;硕士生
电话：15776698528


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月22日(星期一) 中午1:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [nju-softeng/dingtalk-app-back-end] refactor(后端接口 restful 化) (Issue #61)





 
记得之前我在哪个分支上看到一个说明，说钉钉只支持get、post方法。如果是这样，就没办法设计RESTFul风格的接口了吧

**Comment by zhanyeye** [comment]
此外，学弟收到这封邮件，时因为我创建了一个project，添加了一个任务，github 自动生成了一个 issue, 学弟后面带新人时，也可以用到这个功能管理需求

**Comment by lilingj** [comment]
明白
