### ISSUE TITLE
refactor(VoteService)

### ISSUE THREAD

**Issue by lilingj** [nju-softeng/dingtalk-app-server#65]
注意到用户投一张票，调用一次poll函数，只会在vote_detail表中添加一条记录，不会产生ac_record，这段代码没有必要。
https://github.com/nju-softeng/dingtalk-app-server/blob/ebdeb990f4ac21e8a47da043434491d9d59bc0b2/src/main/java/com/softeng/dingtalk/service/VoteService.java#L317-L322

**Comment by zhanyeye** [comment]
这个函数是用来计算投票的AC值的，可能会存在用户修改投票结果的情况，比如 `reject` -> `accept`, 这时需要将旧的ac_record数据删除,重新持久化新的ac_record, "upsert"好像不划算

**Comment by lilingj** [comment]
我读了一下源码，在段代码调用之前，是不会生成对应的ac_record记录的，用户修改投票结果只会修改到vote_detail记录。只有投票结束后，才会生成对应的ac_record记录。

**Comment by zhanyeye** [comment]
你看调用它的地方，这里是在更新论文的投稿结果，这里是要计算论文ac的，论文的投稿结果是有可能被修改的。

https://github.com/nju-softeng/dingtalk-app-server/blob/ebdeb990f4ac21e8a47da043434491d9d59bc0b2/src/main/java/com/softeng/dingtalk/controller/PaperController.java#L99-L104

**Comment by lilingj** [comment]
明白了。那这块应该是没问题了。

**Comment by zhanyeye** [comment]
你/我后面可以给这里补充注释，以防后来人误会了
