### ISSUE TITLE
refactor(string append): can concatenate strings using string placeholders

### ISSUE THREAD

**Issue by zhanyeye** [nju-softeng/dingtalk-app-server#66]
https://github.com/nju-softeng/dingtalk-app-server/blob/ebdeb990f4ac21e8a47da043434491d9d59bc0b2/src/main/java/com/softeng/dingtalk/component/Timer.java#L115-L121
是否需要用 String.format 代替  append(), 性能和可读性的权衡？
https://cowtowncoder.medium.com/measuring-performance-of-java-string-format-or-lack-thereof-2e1c6a13362c

**Comment by lilingj** [comment]
可以把消息主体提取出来，做成消息模板，与某个类绑定，生成消息。（我记得golang里标准库有html/template这个库，就是干这个事的

**Comment by zhanyeye** [comment]
好主意，有时间可以教教我，我也学习一下~

**Comment by lilingj** [comment]
相当于前后端不分离时用后端做渲染，我新开个issue，有时间就重构这一部分
