### ISSUE TITLE
refactor(login): The user can log in after completing the information

### ISSUE THREAD

**Issue by lilingj** [nju-softeng/dingtalk-app-server#71]
个人想法：
1. 做一个拦截器，检测登录用户信息是否完善，如果不完善，强制完善后才可进入系统。
2. 信息包括：
    1. 学号：用学号前缀来确定部分用户职位（比如他们要区分学硕和专硕）
    2. ……

**Comment by zhanyeye** [comment]
哇~，这个idea好~！
+ 信息不完善的用户，每次登录都都提示一个提示+修改的对话框，不用完全拦截（提前来的学生可能不知道自己学号），也方便实现。
挺好的！
