### ISSUE TITLE
refactor(DcRecord): Delete the fields of the table and reconstruct the corresponding code

### ISSUE THREAD

**Issue by lilingj** [nju-softeng/dingtalk-app-server#72]
DcRecord的表字段：`id、dvalue、cvalue、dc、ac、status、insert_time、yearmonth、week、weekdate、version、datecode、applicant_id、auditor_id、（ac_items)`
重构为：`id、dvalue、cvalue、status、insert_time、year_month_week、version、applicant_id、auditor_id`
说明：
1. 删除dc：dc可以在dao层用`select dvalue * cvalue as dc ……`算出来
2. 删除ac和ac_items：这功能单独提出来
3. yearmonth、week、weekdate、datecode由year_month_week替代：yyyyMMww这样的整数应该可以替代这些字段的功能

**Comment by lilingj** [comment]
将整型的year_month_week包装为一个myDate类，在JPA中用@Converter做一个整型和对象的互相转换。myDate类提供getYear，getMonth，getWeek方法。

**Comment by zhanyeye** [comment]
这个地方，我有一点纠结，我也想这样做，面向对象的思想~
但是下学期，上高级数据库的时候，老师会说这样违反数据库第一范式
而且可能导致有些特殊的查询会比较麻烦

**Comment by zhanyeye** [comment]
如果我们检查没有遇到问题，那就这样弄！

**Comment by lilingj** [comment]
> 这个地方，我有一点纠结，我也想这样做，面向对象的思想~ 但是下学期，上高级数据库的时候，老师会说这样违反数据库第一范式 而且可能导致有些特殊的查询会比较麻烦

我看了一下，第一范式强调列的原子性，但是我感觉year_month_week分开不分开都是可以的，作为一个我们定义的时间，它和insert_time差不多，这样看它也是原子的。
