### ISSUE TITLE
refactor(ac_items, ac_record): ac_items table is redundant

### ISSUE THREAD

**Issue by lilingj** [nju-softeng/dingtalk-app-server#73]
问题：ac_items表是多余的，信息和ac_record表重复
方案：删除ac_items表，在ac_record表中加入类似dc_record表的status字段
另外：status应该增加状态，比如增加审核不通过状态

**Comment by zhanyeye** [comment]
这个可以的，当时的设计思路是ac_record和它的名字一样，只存有意义的记录
感觉这么改可能更方便，接近现实情况
