### ISSUE TITLE
bug(dc_record): dc summary problem

### ISSUE THREAD

**Issue by lilingj** [nju-softeng/dingtalk-app-server#74]
问题：计算某周dc时没有排除未审核的dc，即没有加上`where status <> 0`。没出问题是因为未审核的dc记录c值为0
https://github.com/nju-softeng/dingtalk-app-server/blob/be175b7a37450da4e85e76d0486a8b1c1a5c6086/src/main/java/com/softeng/dingtalk/repository/DcRecordRepository.java#L137-L146

**Comment by zhanyeye** [comment]
因为当时就是这么考虑的，这种只有两个值的字段不好加索引，可能觉得筛选条件写太多影响可读性和效率
