### ISSUE TITLE
refactor(internal_paper, external_paper): Merge into one table

### ISSUE THREAD

**Issue by lilingj** [nju-softeng/dingtalk-app-server#75]
问题：外部论文和内部论文两张表没多大差别，代码冗余。
方案：合成一张表，加个is_external字段，前端增加相应的是否是外部论文的选项，如果不是，扩展必填字段，如果是，直接提交。

**Comment by zhanyeye** [comment]
这个可以，因为external_paper 是后期出来的一个需求，是一个临时的实现
