### ISSUE TITLE
启动项目

### ISSUE THREAD

**Issue by daddy-id** [nju-softeng/dingtalk-app-server#92]
如何启动该项目

**Comment by zhanyeye** [comment]
你好，需要先在钉钉开发平台，创建微应用，获取相关配置，修改[项目配置](https://github.com/nju-softeng/dingtalk-app-server/blob/main/src/main/resources/application-dev.properties) 
1. 确认你准备好了 jdk11, mysql8, nodejs 环境 
2. 第一次运行时会报：你的ip不在访问白名单中，需要你去钉钉开放平台配置。
3. 配置好后运行前后端项目就可以了
